language: python
python:
  - "2.7"
  - "3.6"
notifications:
  email: false

# conda setup copied from the conda docs
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - echo ". /home/travis/miniconda/etc/profile.d/conda.sh" >> ~/.bashrc
  - source ~/.bashrc
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda config --add channels pennmem
  - conda update -q conda
  - conda info -a
  - conda install -n base conda-build
  - conda build --output-folder=build/ --python $TRAVIS_PYTHON_VERSION conda.recipe/
  - conda create -n ramutils python=$TRAVIS_PYTHON_VERSION
  - conda activate ramutils
  - conda install build/linux-64/ramutils-*.tar.bz2
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install mock futures;
    fi
  - python --version
  - conda install --file=requirements.txt
script:
  - python -m pytest -m "not rhino" --cov
after_success:
  - codecov
