language: python
python:
  - "2.7"
  - "3.6"
notifications:
  email: false

# conda setup copied from the conda docs
install:
  - sudo apt-get update
  # We do this conditionally because it saves us some downloading if the
  # version is the same.
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      wget https://repo.continuum.io/miniconda/Miniconda2-latest-Linux-x86_64.sh -O miniconda.sh;
    else
      wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
    fi
  - bash miniconda.sh -b -p $HOME/miniconda
  - echo ". /home/travis/miniconda/etc/profile.d/conda.sh" >> ~/.bashrc
  - source ~/.bashrc
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda update -q conda
  - conda info -a
  - conda install -y -n base conda-build
  - python maint/build.py --no-convert --python $TRAVIS_PYTHON_VERSION
  - conda create -n ramutils python=$TRAVIS_PYTHON_VERSION
  - conda activate ramutils
  - conda install -y -c pennmem build/linux-64/ramutils-*.tar.bz2
  # - conda install -y -c pennmem -c conda-forge --file=requirements.txt
  - if [[ "$TRAVIS_PYTHON_VERSION" == "2.7" ]]; then
      conda install -y mock futures;
    fi
  - python --version
  - pip install codecov
script:
  - python -m pytest -m "not rhino" --cov
after_success:
  - codecov
