name: ramutils
channels:
- pennmem
- defaults
dependencies:
- dask=0.15.3
- distributed=1.19.1
- graphviz=2.38.0
- h5py=2.7.0
- hdf5=1.10.1
- matplotlib==2.0.2
- numpy=1.13.3
- pandas=0.20.3
- prompt_toolkit=1.0.15
- psutil=5.4.0
- pytables=3.4.2
- pytest=3.2.1
- pytest-cov=2.5.1
- pywavelets=0.5.2
- pyzmq=16.0.2
- scikit-learn=0.19.1
- scipy=1.0.0
- setuptools=27.2.0
- six=1.10.0
- sphinx=1.6.3
- sphinxcontrib=1.0
- sphinxcontrib-websupport=1.0.1
- statsmodels=0.8.0
- tornado=4.5.2
- traitlets=4.3.2
- traits=4.6.0
- typing=3.6.2
- xarray=0.9.6
- zeromq=4.2.2
- ptsa=1.1.3
