# Read data from setup.py
{% set setup_data = load_setup_py_data() %}

package:
  name: ramutils # {{ setup_data['name'] }}
  version: {{ setup_data['version'] }}

source:
  git_url: ../

build:
  # If this is a new build for the same version, increment the build number by
  # setting the PKG_BUILDNUM environment variable. Without setting, this
  # defaults to 0.
  number: 1

  # Specify additional env vars pass through.
  # Variables that are accessible by default are documented at:
  # https://conda.io/docs/user-guide/tasks/build-packages/environment-variables.html
  #
  script_env:
    # Specified to build a conda package with the latest revision on Travis CI.
    # Otherwise, packages only get built for the latest git version tag.
    - TRAVIS_CI

# Common dependencies that need to be listed in both the build and run
# subsections of the requirements section.
# FIXME: figure out how to set this elsewhere so they only need to be defined
#        once
{%
set deps = [
    "bptools=1.3.0",
    "classiflib=0.1.2",
    "dask>=0.15.3",
    "graphviz>=2.38.0",
    "h5py>=2.7.0",
    "hdf5>=1.10.1",
    "numpy>=1.13.3",
    "pandas>=0.23.1",
    "ptsa>=2.0.0",
    "pymc3=3.2",
    "scikit-learn=0.19.1",
    "scipy>=1.0.0",
    "statsmodels>=0.8.0",
    "traitlets>=4.3.2",
    "traits>=4.6.0",
    "traitschema>=1.1.3",
    "xarray>=0.9.6",
    "gitpython>=2.1.3",
]
%}

# Dependencies require the pennmem channel
requirements:
  build:
    - python {{ python }}
    - setuptools
    {% for dep in deps %}
    - {{ dep }}
    {% endfor %}
  run:
    - python {{ python }}
    {% for dep in deps %}
    - {{ dep }}
    {% endfor %}
    # - vs2015_runtime  [win]

test:
  # Test that we can import the package
  imports:
    - ramutils

about:
  home: {{ setup_data['url'] }}
  summary: {{ setup_data['description'] }}
  # license: FIXME
  # license_file: FIXME
